/* Código da ferramenta para a versão Apps Script (carregado de fora para o Apps Script não interferir).
   Gerado a partir de chuva/index.html. Depende de window.BASE_DADOS, definido na página. */

const LEVELS=[
{id:'nao_significativa',rank:0,fill:'#BFEAF2',stroke:'#8FCBD6',label:'Chuva Não Significativa'},
{id:'baixo',rank:1,fill:'#28E3F0',stroke:'#20B7C0',label:'20–40 mm'},
{id:'medio',rank:2,fill:'#21ADF3',stroke:'#178BC4',label:'40–60 mm'},
{id:'alto',rank:3,fill:'#0E6DFA',stroke:'#0B57C8',label:'60–80 mm'},
{id:'muitoalto',rank:4,fill:'#191EB4',stroke:'#111579',label:'Acima de 80 mm'}];
let selected=LEVELS[0], product='chuva';
const MG_MASK=((window.BRASIL_ESTADOS&&BRASIL_ESTADOS.features)||[]).find(f=>f.properties.UF==='MG')||turf.union(turf.featureCollection(MESO.features));
const map=L.map('map',{zoomControl:true,attributionControl:false,minZoom:5,maxZoom:12});
const drawnItems=new L.FeatureGroup().addTo(map);
L.geoJSON(BRASIL_ESTADOS,{style:f=>({color:f.properties.UF==='MG'?'#777':'#c8c8c8',weight:f.properties.UF==='MG'?0.5:1,fillColor:'#fff',fillOpacity:1})}).addTo(map);
const mesoDisplay=L.geoJSON(MESO,{style:{color:'#454545',weight:1.15,fillOpacity:0}}).addTo(map); map.fitBounds(mesoDisplay.getBounds(),{padding:[25,25]});
L.geoJSON(CIDADES,{pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:3.1,color:'#111',weight:1.4,fillColor:'#fff',fillOpacity:1}),onEachFeature:(f,l)=>{const n=f.properties.NM_LOCAL_1||f.properties.NM_MUNICIP||f.properties.nome||'';l.bindTooltip(n,{permanent:true,direction:'right',offset:[5,-3],className:'city-label'});}}).addTo(map);
function levelById(id){return LEVELS.find(x=>x.id===id)||LEVELS[0]} function styleFor(l){return {color:l.stroke,weight:1.5,fillColor:l.fill,fillOpacity:1}}
function renderLevels(){const el=document.getElementById('levels');el.innerHTML='';LEVELS.forEach(l=>{const b=document.createElement('button');b.className='level'+(l.id===selected.id?' active':'');b.innerHTML=`<span class="swatch" style="background:${l.fill}"></span>${l.label}`;b.onclick=()=>{selected=l;document.getElementById('currentLabel').textContent=l.label;renderLevels()};el.appendChild(b)});renderLegend();}
function renderLegend(){document.getElementById('legend').innerHTML=LEVELS.slice().reverse().map(l=>`<div><span class="swatch" style="background:${l.fill}"></span>${l.label}</div>`).join('')+'<div><span class="swatch" style="background:#fff"></span>Sem Previsão de Chuvas</div>'}
function renderLabelEditor(){const el=document.getElementById('labelEditor');el.innerHTML='';LEVELS.forEach(l=>{const r=document.createElement('div');r.className='labelrow';r.innerHTML=`<span class="swatch" style="background:${l.fill}"></span><input value="${l.label}" data-id="${l.id}">`;r.querySelector('input').oninput=e=>{l.label=e.target.value; if(selected.id===l.id)document.getElementById('currentLabel').textContent=l.label;renderLevels()};el.appendChild(r)})}
renderLabelEditor();renderLevels();
function setStatus(s){document.getElementById('status').textContent=s}
function clipFeature(f){try{return turf.intersect(turf.featureCollection([f,MG_MASK]))}catch(e){return null}}
function addFeature(f,id){const cl=clipFeature(f);if(!cl)return;const lv=levelById(id);L.geoJSON(cl,{style:styleFor(lv),onEachFeature:(ff,l)=>{l._level=id;drawnItems.addLayer(l);l.bindPopup(`<b>${lv.label}</b><br><button onclick="window.delLayer(${L.Util.stamp(l)})">Excluir</button>`);}});refreshZ()}
window.delLayer=id=>{drawnItems.eachLayer(l=>{if(L.Util.stamp(l)===id)drawnItems.removeLayer(l)});refreshZ()}
function refreshZ(){LEVELS.forEach(lv=>drawnItems.eachLayer(l=>{if(l._level===lv.id&&l.bringToFront)l.bringToFront()}))}
let drawControl;document.getElementById('drawBtn').onclick=()=>{drawControl=new L.Draw.Polygon(map,{allowIntersection:false,showArea:false,shapeOptions:styleFor(selected)});drawControl.enable();setStatus('Desenhando '+selected.label+'...')};
map.on(L.Draw.Event.CREATED,e=>{const f=e.layer.toGeoJSON();addFeature(f,selected.id);setStatus('Área criada e recortada no limite de Minas Gerais.')});
function features(){const a=[];drawnItems.eachLayer(l=>{const f=l.toGeoJSON();f.properties={level:l._level};a.push(f)});return a}
document.getElementById('clearBtn').onclick=()=>{if(confirm('Apagar todas as áreas deste produto?')){drawnItems.clearLayers();localStorage.removeItem('simge-chuva-tend-v02-'+product);setStatus('Áreas apagadas.')}};
document.getElementById('saveBtn').onclick=()=>{localStorage.setItem('simge-chuva-tend-v02-'+product,JSON.stringify(features()));setStatus('Produto salvo neste navegador.')};
function loadProduct(){drawnItems.clearLayers();try{const arr=JSON.parse(localStorage.getItem('simge-chuva-tend-v02-'+product)||'[]');arr.forEach(f=>addFeature(f,f.properties.level));}catch(e){}}
function switchProduct(p){product=p;document.getElementById('tabChuva').classList.toggle('active',p==='chuva');document.getElementById('tabTend').classList.toggle('active',p==='tendencia');document.getElementById('trendDates').style.display=p==='tendencia'?'block':'none';loadProduct();setStatus(p==='chuva'?'Modo Previsão de Chuva.':'Modo Tendência 48h.')}
document.getElementById('tabChuva').onclick=()=>switchProduct('chuva');document.getElementById('tabTend').onclick=()=>switchProduct('tendencia');
function iso(d){return d.toISOString().slice(0,10)};function initDates(){const d=new Date();forecastDate.value=iso(d);const d1=new Date(d);d1.setDate(d.getDate()+1);const d2=new Date(d);d2.setDate(d.getDate()+2);trendDate1.value=iso(d1);trendDate2.value=iso(d2);const v=new Date(d);v.setDate(v.getDate()+1);v.setHours(10,0,0,0);validUntil.value=`${iso(v)}T10:00`}initDates();loadProduct();
function brDate(v){if(!v)return '';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function projectFactory(w,h,pad=42){const minx=-52.5,maxx=-37.5,miny=-23.0,maxy=-14.0;const sx=(w-2*pad)/(maxx-minx),sy=(h-2*pad)/(maxy-miny),s=Math.min(sx,sy);const ox=(w-(maxx-minx)*s)/2-minx*s,oy=(h-(maxy-miny)*s)/2+maxy*s;return c=>[c[0]*s+ox,oy-c[1]*s]}
function drawGeom(ctx,geom,proj,style){ctx.save();ctx.beginPath();const polys=geom.type==='Polygon'?[geom.coordinates]:geom.coordinates;for(const poly of polys){for(const ring of poly){ring.forEach((c,i)=>{const [x,y]=proj(c);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}}ctx.fillStyle=style.fill;ctx.globalAlpha=style.fillOpacity??1;ctx.fill('evenodd');ctx.globalAlpha=1;ctx.strokeStyle=style.stroke;ctx.lineWidth=style.width??1;ctx.stroke();ctx.restore()}
function drawLabels(ctx,proj){const labels=[['GO',-50.05,-16.65],['BA',-41.2,-15.15],['ES',-40.65,-19.25],['RJ',-42.45,-22.05],['SP',-49.25,-21.75]];ctx.save();ctx.font='bold 22px Arial';ctx.fillStyle='#111';labels.forEach(([t,x,y])=>{const p=proj([x,y]);ctx.fillText(t,p[0],p[1])});ctx.restore()}
function fmtLon(v){const d=Math.abs(v),deg=Math.floor(d),min=Math.round((d-deg)*60);return `${deg}°${String(min).padStart(2,'0')}′00″W`} function fmtLat(v){const d=Math.abs(v),deg=Math.floor(d),min=Math.round((d-deg)*60);return `${deg}°${String(min).padStart(2,'0')}′00″S`}
function frame(ctx,w,h){const m=30;ctx.save();ctx.strokeStyle='#222';ctx.lineWidth=1.6;ctx.strokeRect(m,m,w-2*m,h-2*m);ctx.restore()}
function graticule(ctx,proj,w,h){const lons=[-51,-49.5,-48,-46.5,-45,-43.5,-42,-40.5,-39,-37.5],lats=[-15,-16.5,-18,-19.5,-21,-22.5],m=30;ctx.save();ctx.font='15px Arial';ctx.fillStyle='#111';ctx.textBaseline='middle';lons.forEach(l=>{const x=proj([l,-14.5])[0],t=fmtLon(l),tw=ctx.measureText(t).width;ctx.fillText(t,x-tw/2,m/2-1);ctx.fillText(t,x-tw/2,h-m/2+1)});lats.forEach(a=>{const y=proj([-52,a])[1],t=fmtLat(a);ctx.save();ctx.translate(m/2,y);ctx.rotate(-Math.PI/2);ctx.textAlign='center';ctx.fillText(t,0,0);ctx.restore();ctx.save();ctx.translate(w-m/2,y);ctx.rotate(Math.PI/2);ctx.textAlign='center';ctx.fillText(t,0,0);ctx.restore()});ctx.restore()}
function scaleBar(ctx){const x=58,y=ctx.canvas.height-62,w=80;ctx.save();ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.moveTo(x,y-8);ctx.lineTo(x,y+8);ctx.moveTo(x+w/2,y-8);ctx.lineTo(x+w/2,y+8);ctx.moveTo(x+w,y-8);ctx.lineTo(x+w,y+8);ctx.stroke();ctx.font='15px Arial';ctx.fillText('0',x-4,y-18);ctx.fillText('50',x+w/2-8,y-18);ctx.fillText('100 km',x+w-10,y-18);ctx.beginPath();ctx.moveTo(x+2,y-34);ctx.lineTo(x+14,y-72);ctx.lineTo(x+27,y-34);ctx.lineTo(x+15,y-46);ctx.closePath();ctx.stroke();ctx.restore()}
function union(fs){if(!fs.length)return null;if(fs.length===1)return fs[0];try{return turf.union(turf.featureCollection(fs))}catch(e){return fs[0]}}
function visibleFeatures(){const src=features().map(f=>{const c=clipFeature(f);if(c)c.properties=f.properties;return c}).filter(Boolean),out=[];let high=null;for(const lv of LEVELS.slice().sort((a,b)=>b.rank-a.rank)){const same=src.filter(f=>f.properties.level===lv.id);for(const f of same){let v=f;if(high){try{v=turf.difference(turf.featureCollection([f,high]))}catch(e){}}if(v){v.properties={level:lv.id};out.push(v)}}const m=union(same);if(m)high=high?union([high,m]):m}return out.sort((a,b)=>levelById(a.properties.level).rank-levelById(b.properties.level).rank)}
async function generatePNG(){const sheet=document.getElementById('printSheet'),canvas=document.getElementById('printCanvas'),ctx=canvas.getContext('2d'),proj=projectFactory(canvas.width,canvas.height);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);
BRASIL_ESTADOS.features.forEach(f=>drawGeom(ctx,f.geometry,proj,{fill:'#fff',fillOpacity:1,stroke:'#c4c4c4',width:1}));
visibleFeatures().forEach(f=>{const lv=levelById(f.properties.level);drawGeom(ctx,f.geometry,proj,{fill:lv.fill,fillOpacity:1,stroke:lv.stroke,width:1.2})});
MESO.features.forEach(f=>drawGeom(ctx,f.geometry,proj,{fill:'#000',fillOpacity:0,stroke:'#333',width:1.15}));drawGeom(ctx,MG_MASK.geometry,proj,{fill:'#000',fillOpacity:0,stroke:'#222',width:1.4});
ctx.font='16px Arial';for(const f of CIDADES.features){const [x,y]=proj(f.geometry.coordinates),n=f.properties.NM_LOCAL_1||f.properties.NM_MUNICIP||'';ctx.beginPath();ctx.arc(x,y,6.5,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.strokeText(n,x+10,y-8);ctx.fillStyle='#111';ctx.fillText(n,x+10,y-8)}
drawLabels(ctx,proj);frame(ctx,canvas.width,canvas.height);graticule(ctx,proj,canvas.width,canvas.height);scaleBar(ctx);
const fd=forecastDate.value;if(product==='chuva')printTitle.textContent=`Previsão de Chuva - ${brDate(fd)}*`;else printTitle.textContent=`Tendência - ${brDate(trendDate1.value).slice(0,5)} e ${brDate(trendDate2.value).slice(0,5)}*`;
const used=LEVELS.filter(l=>features().some(f=>f.properties.level===l.id)).sort((a,b)=>b.rank-a.rank);printLegend.innerHTML='<b style="font-size:20px">Legenda</b><br>'+used.map(l=>`<div><span style="display:inline-block;width:24px;height:18px;background:${l.fill};border:1px solid #777;margin-right:10px;vertical-align:-3px"></span>${l.label}</div>`).join('')+'<div><span style="display:inline-block;width:24px;height:18px;background:#fff;border:1px solid #777;margin-right:10px;vertical-align:-3px"></span>Sem Previsão de Chuvas</div>';
const dt=validUntil.value?new Date(validUntil.value):null;printValidity.textContent=dt?`*Válido até às ${String(dt.getHours()).padStart(2,'0')}h do dia ${String(dt.getDate()).padStart(2,'0')}/${String(dt.getMonth()+1).padStart(2,'0')}/${dt.getFullYear()}.`:'';printCredits.innerHTML='Projeção: Latitude/Longitude - Datum SIRGAS2000<br>MESORREGIÕES/MG - IGAM, 2009<br>Previsão de Tempo - SIMGE/IGAM, 2026';
sheet.style.display='block';await new Promise(r=>setTimeout(r,100));const out=await html2canvas(sheet,{backgroundColor:'#fff',scale:1,useCORS:true});sheet.style.display='none';const a=document.createElement('a');a.download=(product==='chuva'?'chuva_':'tendencia_')+(fd||'mapa').replaceAll('-','')+'.png';a.href=out.toDataURL('image/png');a.click();setStatus('PNG gerado.')}
pngBtn.onclick=generatePNG;
